/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.istloja.vistas;

import com.istloja.controlador.Inventariodb;
import com.istloja.modelTablas.ModelTableInventario;

/**
 *
 * @author Usuario
 */
public class BusquedaAvanzada extends javax.swing.JDialog {

    private ModelTableInventario modelTableInventario;
    private Inventariodb controladorInventario;

    public BusquedaAvanzada(java.awt.Frame parent, boolean modal, ModelTableInventario modelTableInventario, Inventariodb controladorInventario) {
        super(parent, modal);
        this.modelTableInventario = modelTableInventario;
        this.controladorInventario = controladorInventario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbBusquedaAvanzada = new javax.swing.JLabel();
        jcbBusquedaAvanzada = new javax.swing.JComboBox<>();
        jtxtBusquedaAvanzada = new javax.swing.JTextField();
        jbtnBusquedaAvanzada = new javax.swing.JButton();
        JPanel1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlbBusquedaAvanzada.setText("Busqueda");

        jcbBusquedaAvanzada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CódigoProducto", "Descripción" }));

        jbtnBusquedaAvanzada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/resource/img/Busqueda_Avanzada.png"))); // NOI18N
        jbtnBusquedaAvanzada.setText("BUSCAR");
        jbtnBusquedaAvanzada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBusquedaAvanzadaActionPerformed(evt);
            }
        });

        jTable1.setModel( modelTableInventario);
        JPanel1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPanel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbBusquedaAvanzada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbBusquedaAvanzada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtBusquedaAvanzada, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jbtnBusquedaAvanzada)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbBusquedaAvanzada)
                    .addComponent(jcbBusquedaAvanzada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtBusquedaAvanzada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBusquedaAvanzada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBusquedaAvanzadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBusquedaAvanzadaActionPerformed
        switch (jcbBusquedaAvanzada.getSelectedIndex()) {
            case 0://Codigo Producto  
                modelTableInventario.setInventario(controladorInventario.obtenerProductosInventariosCodigo(jtxtBusquedaAvanzada.getText()));
                modelTableInventario.fireTableDataChanged();
                break;
            case 1: //Descripcion Producto 
                modelTableInventario.setInventario(controladorInventario.obtenerProductosInventariosDescripcion(jtxtBusquedaAvanzada.getText()));
                modelTableInventario.fireTableDataChanged();
                break;
    }//GEN-LAST:event_jbtnBusquedaAvanzadaActionPerformed

    /**
         * @param args the command line arguments
         */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnBusquedaAvanzada;
    private javax.swing.JComboBox<String> jcbBusquedaAvanzada;
    private javax.swing.JLabel jlbBusquedaAvanzada;
    private javax.swing.JTextField jtxtBusquedaAvanzada;
    // End of variables declaration//GEN-END:variables

}
